remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ["The Why's, What's and How's of Grad School Applications"]
description: ["A CMU SCS perspective"] # ["Information about webinars on various aspects of graduate school applications"]
